import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import prisma from "../../lib/prisma";
import {
  Table,
  Thead,
  Tbody,
  Tfoot,
  Tr,
  Th,
  Td,
  TableCaption,
  TableContainer,
  ButtonGroup,
  Button,
} from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ books }) {
  return (
    <>
      <Head>
        <title>Homework-w14</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <h1>Homepage</h1>
        {JSON.stringify(books)} */}
        <TableContainer>
          <Table variant="striped" colorScheme="teal">
            <TableCaption>Books List</TableCaption>
            <Thead>
              <Tr>
                <Th>Title</Th>
                <Th>Author</Th>
                <Th>Publisher</Th>
                <Th>Pages</Th>
                <Th>Year</Th>
                <Th>Image</Th>
                <Th>Action</Th>
              </Tr>
            </Thead>
            <Tbody>
              {books.map((book, index) => {
                return (
                  <Tr key={index}>
                    <Td>{book.title}</Td>
                    <Td>{book.author}</Td>
                    <Td>{book.publisher}</Td>
                    <Td>{book.pages}</Td>
                    <Td>{book.year}</Td>
                    <Td>{book.image}</Td>
                    <Td>
                      <ButtonGroup>
                        <Button>Detail</Button>
                        <Button>Edit</Button>
                        <Button>Delete</Button>
                      </ButtonGroup>
                    </Td>
                  </Tr>
                );
              })}
            </Tbody>
          </Table>
        </TableContainer>
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  let books = await prisma.Book.findMany();
  books = JSON.parse(JSON.stringify(books));

  return {
    props: { books },
  };
};
